@startuml

title MVCモデル

hide footbox

actor ユーザー as user
box ウィジェット（UIコンポーネントを指す）
participant View as view
participant Controller as controller
end box
participant Model as model

user -> controller: ユーザーが入力する
activate controller

controller -> model: 入力を受け、コマンドを送る
deactivate controller
activate model

model -> model: コマンドを受けて処理を行い、\n自身を更新する

view -> model: Modelの変更を監視する（Observerパターン）
deactivate model
activate view

view -> view: Modelに更新があった場合は、\n自身を更新する

view -> user: ユーザーに表示する
deactivate view

@enduml